export const PROJECTS = [
  {
    "name":"CASA C.D.",
    "url":"casa-cd",
    "thumbnail_o":"images/casa-cd/1.jpg",
    "thumbnail_v":"images/casa-cd/8.jpg",
    "image":["images/casa-cd/1.jpg",
    "images/casa-cd/2.jpg",
    "images/casa-cd/3.jpg",
    "images/casa-cd/4.jpg",
    "images/casa-cd/5.jpg",
    "images/casa-cd/6.jpg",
    "images/casa-cd/7.jpg",
    "images/casa-cd/8.jpg",
    "images/casa-cd/9.jpg",
    "images/casa-cd/10.jpg",
    "images/casa-cd/11.jpg",
    "images/casa-cd/12.jpg",
    "images/casa-cd/13.jpg",
    "images/casa-cd/14.jpg",
    "images/casa-cd/15.jpg",
    "images/casa-cd/16.jpg",
    "images/casa-cd/17.jpg",
    "images/casa-cd/18.jpg",
    "images/casa-cd/19.jpg",
    "images/casa-cd/20.jpg",
    "images/casa-cd/21.jpg",
    "images/casa-cd/22.jpg",
    "images/casa-cd/23.jpg",
    "images/casa-cd/24.jpg",
    "images/casa-cd/25.jpg",
    "images/casa-cd/26.jpg",
    "images/casa-cd/27.jpg",
    "images/casa-cd/28.jpg"],
    "type":"Ristrutturazione e ampliamento",
    "year":"2020",
    "location":"Fossombrone (PU)",
    "dimensions":"320mq"
  },

  {
    "name":"CASA P.A.",
    "url":"casa-pa",
    "thumbnail_o":"images/casa-pa/1.jpg",
    "thumbnail_v":"images/casa-pa/2.jpg",
    "image":["images/casa-pa/1.jpg",
    "images/casa-pa/2.jpg",
    "images/casa-pa/3.jpg",
    "images/casa-pa/4.jpg",
    "images/casa-pa/5.jpg",
    "images/casa-pa/6.jpg",
    "images/casa-pa/7.jpg",
    "images/casa-pa/8.jpg",
    "images/casa-pa/9.jpg",
    "images/casa-pa/10.jpg",
    "images/casa-pa/11.jpg",
    "images/casa-pa/12.jpg",
    "images/casa-pa/13.jpg",
    "images/casa-pa/14.jpg",
    "images/casa-pa/15.jpg",
    "images/casa-pa/16.jpg",
    "images/casa-pa/17.jpg"],
    "type":"Ristrutturazione",
    "year":"2004",
    "location":"Fossombrone (PU)",
    "dimensions":"353mq",
    "photography":"Vito Corvasce"
  },

  {
    "name":"CASA S.S.",
    "url":"casa-ss",
    "thumbnail_o":"images/casa-sf/1.jpg",
    "thumbnail_v":"images/casa-sf/7.jpg",
    "image":["images/casa-sf/1.jpg",
    "images/casa-sf/2.jpg",
    "images/casa-sf/3.jpg",
    "images/casa-sf/4.jpg",
    "images/casa-sf/5.jpg",
    "images/casa-sf/6.jpg",
    "images/casa-sf/7.jpg",
    "images/casa-sf/8.jpg",
    "images/casa-sf/9.jpg",
    "images/casa-sf/10.jpg",
    "images/casa-sf/11.jpg",
    "images/casa-sf/12.jpg",
    "images/casa-sf/13.jpg",
    "images/casa-sf/14.jpg"],
    "type":"Nuova Costruzione",
    "year":"2015",
    "location":"Caparazzino  (PU)",
    "dimensions":"240mq",
    "photography":"Enrico Barbaresi"
  },

  {
    "name":"CASA C.G.",
    "url":"casa-cg",
    "thumbnail_o":"images/casa-gg/1.jpg",
    "thumbnail_v":"images/casa-gg/7.jpg",
    "image":["images/casa-gg/1.jpg",
    "images/casa-gg/2.jpg",
    "images/casa-gg/3.jpg",
    "images/casa-gg/4.jpg",
    "images/casa-gg/5.jpg",
    "images/casa-gg/6.jpg",
    "images/casa-gg/7.jpg",
    "images/casa-gg/8.jpg",
    "images/casa-gg/9.jpg",
    "images/casa-gg/10.jpg",
    "images/casa-gg/11.jpg",
    "images/casa-gg/12.jpg",
    "images/casa-gg/13.jpg"],
    "type":"Ristrutturazione",
    "year":"2010",
    "location":"Pietrarubbia  (PU)",
    "dimensions":"170mq",
    "photography":"Enrico Barbaresi"
  },

  {
    "name":"CASA E.S.",
    "url":"casa-es",
    "thumbnail_o":"images/casa-es/1.jpg",
    "thumbnail_v":"images/casa-es/2.jpg",
    "image":["images/casa-es/1.jpg",
    "images/casa-es/2.jpg",
    "images/casa-es/3.jpg",
    "images/casa-es/4.jpg",
    "images/casa-es/5.jpg",
    "images/casa-es/6.jpg",
    "images/casa-es/7.jpg",
    "images/casa-es/8.jpg",
    "images/casa-es/9.jpg",
    "images/casa-es/10.jpg",
    "images/casa-es/11.jpg"],
    "type":"Ristrutturazione",
    "year":"2013",
    "location":"Fossombrone (PU)",
    "dimensions":"367mq"
  },

  {
    "name":"CASA M.R.",
    "url":"casa-mr",
    "thumbnail_o":"images/casa-rm/1.jpg",
    "thumbnail_v":"images/casa-rm/1.jpg",
    "image":["images/casa-rm/1.jpg",
    "images/casa-rm/2.jpg",
    "images/casa-rm/3.jpg",
    "images/casa-rm/4.jpg",
    "images/casa-rm/5.jpg",
    "images/casa-rm/6.jpg",
    "images/casa-rm/7.jpg",
    "images/casa-rm/8.jpg",
    "images/casa-rm/9.jpg",
    "images/casa-rm/10.jpg",
    "images/casa-rm/11.jpg",
    "images/casa-rm/12.jpg",
    "images/casa-rm/13.jpg"],
    "type":"Ristrutturazione",
    "year":"2007",
    "location":"Mercatale di Sassocorvaro  (PU)",
    "dimensions":"140mq"
  }
];
